### ISSUE TITLE
Does class led can add pulse function use GPIO.pwm?

### ISSUE THREAD

**Issue by ai0** [spoonysonny/SAKS-SDK#1]
led breath effect is also very practical,
so maybe can consider to add pulse function to the led class in led.py?
the effect will like mention in this article:

http://shumeipai.nxez.com/2015/11/18/saks-diy-tutorials-breathing-light.html

**Comment by ai0** [comment]
I had implemented this function and sent a pull requests, thanks for the article.

**Comment by spoonysonny** [comment]
Thanks for your pull request, I will test it and try to merge in next days.
