### ISSUE TITLE
import sakshat 很不方便

### ISSUE THREAD

**Issue by 3b295** [spoonysonny/SAKS-SDK#5]
|__ SKD
|       |__ sakspins.py
|       |__ sakshats.py
|__ run.py 

在run.py 中import sakhats

> ImportError: No module named 'sakpins'

``` python
from sakspins import SAKSPins as PINS
import entities
```

python3 这里会使用绝对导入。自己写的代码如果不在同级目录这里会找不到sakpins。

自己写的东西和这个SDK放一起又比较乱。
作者能写一个setup.py 之类东西吗？(>.<)

**Comment by superfashi** [comment]
写过，你可以使用`pip install sakshat`直接安装，或者在[这里](https://pypi.python.org/pypi/sakshat/0.0.2)下载包并查看更多详情。
顺便推荐你尝试用Go语言编写的SDK，拥有更好的并发、更快的速度和更少的资源占用->[SAKS-SDK-GO](https://github.com/hanbang-wang/SAKS-SDK-GO)
